---
##3any playbook start with three dash
- 
##the minues sign indicate a list of items
  hosts: all
  #3it is the target where my playbook will run
  #varaibles
  #in json the indentation happen with curl braces where as in ansible the indentation happen with two spaces
  vars:
    #variable need to define in key value format
    motd_ubuntu: "Welcome to Ubuntu Linux \n"
    motd_redhat: "Welcome to Redhat \n"
  ##we need to define tasks
  #to define task it start with task block and below the name of the task
  tasks:
    - name: configure message of the day for ubuntu system 
      copy:
        content: "{{motd_ubuntu}}"
        dest: /etc/motd
      notify: MOTD change in Ubuntu
      when: ansible_distribution == "Ubuntu"
    - name: configure message of the day for Redhat system 
      copy:
        content: "{{motd_redhat}}"
        dest: /etc/motd
      notify: MOTD change in Redhat
      when: ansible_distribution == "RedHat"
        ###to call a varaible in python Jinja2
  handlers:
    - name: MOTD Change in Ubuntu
        debug: 
          msg: changes in ubuntu
    - name: MOTD Change in Redhat
        debug: 
          msg: changes in redhat